---
title: "homework02"
author: "Jiapeng Wang"
date: "2023-10-11"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
*Question1:*

```{r, fig.width=10, fig.height=10}
rm(list = ls()) 

n = 1000
data <- read.csv("boxers.csv", header = TRUE, sep = ",")

poi <- seq(65, 90, length.out = 1000)

x = data$reach
y = data$height

model = lm(y ~ x)
predictions <- predict(model, interval = "confidence", level = 0.95)

row1 <- rep(1, 19)

X1 <- rbind(row1, data$reach)
X1 = t(X1)

L <- solve(t(X1) %*% X1)

y_hat = fitted(model)
e = y - y_hat
s = sqrt(sum(e^2) / (19 - 2))
s_y = rep(0,1000)
for (i in 1:1000) {
  xx = matrix(c(1,poi[i]),nrow = 2)
  value <- qf(0.95, df1=2, df2=17, lower.tail=TRUE)
  s_y[i] = s * sqrt(2 * t(xx) %*% L %*% xx * value)
}
newy = rep(0,1000)
for (i in 1:1000) {
  newy[i] = model$coefficients[2]*poi[i] + model$coefficients[1]
}

y_lower = newy - s_y
y_upper = newy + s_y

plot(x, y, main = '95% simultaneous and non-simultaneous confidence bands for boxer data', 
     xlab = 'reach',
     ylab = 'height')
abline(a = model$coefficients[1], b = model$coefficients[2], col='black') 
lines(poi, y_lower, col='red', lty = 1)
lines(poi, y_upper, col='red', lty = 1)
lines(sort(x), sort(predictions[, 2]), col='blue', lty = 1)
lines(sort(x), sort(predictions[, 3]), col='blue', lty = 1)
legend("topleft", 
       cex = 0.9,
       title = "legend",
       legend=c("estimated regression line", "95% simultaneous confidence bands", "95% non-simultaneous confidence bands"), 
       col=c("black", "red", "blue"), 
       lty = c(1, 1, 1))

```

